### ISSUE TITLE
Improve accuracy and visuals of canvas drawing

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#213]
As a user, I want to see a clear and accurate image of forces on a knee, so that I can easily read and understand the data that is being presented to me.

## Definition of Done
- [x] Knee image itself is clear and easy to read
- [x] Forces are accurately represented in the correct colors and areas on the canvas

## Tasks
- [x] #270 
- [x] #271 
- [x] #272 
- [x] #273 
- [x] #274

**Comment by mariotorres1** [comment]
This story took me about 4 total hours to complete. We weren't able to just draw the nodes because the forces in the result file were connecting with each element being drawn which is a connection of 8 or so nodes. That took some time to figure out how to tackle this problem without having to redo much work being it's at the end of the project.
